### ISSUE TITLE
TypeError: Cannot read property 'backend' of undefined

### ISSUE THREAD

**Issue by Shahzayb** [gabrielnic/dfinity-react#6]
I'm getting this error during build (in fleek), even though I created the `canister_ids.json` in the root like this.

```
{
  "backend": {
    "ic": "xyz"
  },
  "frontend": {
    "ic": "xyz"
  }
}
```

```
2:01:32 AM 01/17/2022: > craco build
2:01:33 AM 01/17/2022: No local canister_ids.json found. Continuing production
2:01:33 AM 01/17/2022: /workspace/craco.config.js:55
2:01:33 AM 01/17/2022: BACKEND_CANISTER_ID: canisters['backend'],
2:01:33 AM 01/17/2022: ^
2:01:33 AM 01/17/2022: TypeError: Cannot read property 'backend' of undefined
2:01:33 AM 01/17/2022: at Object.<anonymous> (/workspace/craco.config.js:55:39)
2:01:33 AM 01/17/2022: at Module._compile (node:internal/modules/cjs/loader:1095:14)
2:01:33 AM 01/17/2022: at Object.Module._extensions..js (node:internal/modules/cjs/loader:1124:10)
2:01:33 AM 01/17/2022: at Module.load (node:internal/modules/cjs/loader:975:32)
2:01:33 AM 01/17/2022: at Function.Module._load (node:internal/modules/cjs/loader:816:12)
2:01:33 AM 01/17/2022: at Module.require (node:internal/modules/cjs/loader:999:19)
2:01:33 AM 01/17/2022: at module.exports (/workspace/node_modules/import-fresh/index.js:32:59)
2:01:33 AM 01/17/2022: at loadJs (/workspace/node_modules/cosmiconfig/dist/loaders.js:16:18)
2:01:33 AM 01/17/2022: at ExplorerSync.loadFileContentSync (/workspace/node_modules/cosmiconfig/dist/ExplorerSync.js:84:26)
2:01:33 AM 01/17/2022: at ExplorerSync.createCosmiconfigResultSync (/workspace/node_modules/cosmiconfig/dist/ExplorerSync.js:89:30)
2:01:56 AM 01/17/2022: Error occured during the build.
```

**Comment by Shahzayb** [comment]
Ran the `dfx deploy --network ic` locally and it was working fine.

**Comment by Shahzayb** [comment]
`dfx.json` file content:

```
{
  "canisters": {
    "backend": {
      "main": "src/backend/main.mo",
      "type": "motoko"
    },
    "frontend": {
      "dependencies": ["backend"],
      "frontend": {
        "entrypoint": "build/index.html"
      },
      "source": ["build"],
      "type": "assets"
    }
  },
  "defaults": {
    "build": {
      "output": "canisters",
      "packtool": ""
    }
  },
  "dfx": "0.8.5-beta.0",
  "networks": {
    "local": {
      "bind": "127.0.0.1:8000",
      "type": "ephemeral"
    }
  },
  "version": 1
}

```

**Comment by gabrielnic** [comment]
hi, yeah,I pushed a fix for that. Remove yarn.lock and modules and try again. Also I've upgraded to the latest version: 0.8.6
